#' Interactive Data Dictionary Dictator
#' Generates roxygen2 documentation by prompting the user for column descriptions one by one.

dictate_dictionary <- function() {
  # Find all data frames in the global environment
  env_objs <- ls(envir = .GlobalEnv)
  is_df <- sapply(env_objs, function(x) is.data.frame(get(x, envir = .GlobalEnv)))
  df_names <- env_objs[is_df]
  
  if (length(df_names) == 0) {
    return(message("No data frames found in the global environment."))
  }
  
  # Trigger interactive prompt to select the dataset
  target_df <- select.list(
    choices = df_names,
    title = "Select a dataset to document:"
  )
  
  if (target_df == "") return(message("Documentation cancelled."))
  
  data <- get(target_df, envir = .GlobalEnv)
  cols <- names(data)
  n_rows <- nrow(data)
  n_cols <- ncol(data)
  
  # Ask for high-level documentation
  message(sprintf("\n--- Documenting: '%s' (%d rows, %d columns) ---", target_df, n_rows, n_cols))
  dataset_title <- readline(prompt = "Enter a short title for this dataset: ")
  dataset_desc <- readline(prompt = "Enter a brief 1-2 sentence description: ")
  
  # Loop through columns and ask for inputs one by one
  message("\n--- Enter Column Descriptions ---")
  col_docs <- character(n_cols)
  
  for (i in seq_along(cols)) {
    col_name <- cols[i]
    col_type <- paste(class(data[[col_name]]), collapse = "/")
    
    prompt_text <- sprintf("Desc for '%s' (Type: %s): ", col_name, col_type)
    user_desc <- readline(prompt = prompt_text)
    
    if (trimws(user_desc) == "") user_desc <- "No description provided."
    
    # Format directly into roxygen \item syntax
    col_docs[i] <- sprintf("#'   \\item{%s}{%s. %s}", col_name, col_type, user_desc)
  }
  
  # Assemble the final roxygen block
  roxy_lines <- c(
    sprintf("#' %s", dataset_title),
    "#'",
    sprintf("#' %s", dataset_desc),
    "#'",
    sprintf("#' @format A data frame with %d rows and %d variables:", n_rows, n_cols),
    "#' \\describe{",
    col_docs,
    "#' }",
    sprintf("#' @source Automatically generated by Data Dictionary Dictator"),
    sprintf("\"%s\"\n", target_df)
  )
  
  # Final interactive choice for output
  message("\nDocumentation complete.")
  out_choice <- select.list(
    choices = c("Print to console", "Save to R/data.R"), 
    title = "Where should this documentation go?"
  )
  
  if (out_choice == "Print to console") {
    cat("\n--- Generated Roxygen2 Block ---\n")
    cat(roxy_lines, sep = "\n")
  } else if (out_choice == "Save to R/data.R") {
    if (!dir.exists("R")) dir.create("R")
    write(roxy_lines, file = "R/data.R", append = TRUE)
    message("Success: Documentation appended to R/data.R")
  }
  
  return(invisible(TRUE))
}